name: Rastless-Cli CI/CD Pipeline

on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:
    branches:
      - master
      - main
      - dev

jobs:
  deployment:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
   # if: branch is master
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Update poetry version + build + publish
        run: |
          echo VERSION!!!
          echo $(git describe --tags --abbrev=0)
          poetry version $(git describe --tags --abbrev=0)
          poetry build
          poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
      - name: Create release
        uses: ncipollo/release-action@v1
# create dummy poetry package => poetry build should work local
# create pypi credentials => build release first local
# find out how to create release on latest tag

# tag commit on master
# update version in pyproject.toml
# create release
# on release
# poetry publish + build => from where does poetry take version number?


