name: Rastless-Cli CI/CD Pipeline

on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:
    branches:
      - master
      - main
      - dev

jobs:
  deployment:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
   # if: branch is master
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
 # install poetry
      - name: Install poetry
        run: pipx install poetry==1.2.0
      # set-up python with cache
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      # install requirements
      - name: Install requirements
        run: poetry install --only semver
      # semantic release
      - name: Python Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          set -o pipefail
          # Set git details
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          # run semantic-release
          poetry run semantic-release publish -v DEBUG -D commit_author="github-actions <action@github.com>"
        #uses: ncipollo/release-action@v1

# tag commit on master
# update version in pyproject.toml
# create release
# on release
# poetry publish + build => from where does poetry take version number?


